# Generated by Django 5.2.11 on 2026-03-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Alimento')),
                ('energia_kj', models.IntegerField(blank=True, null=True, verbose_name='Energia (KJ)')),
                ('energia_kcal', models.IntegerField(blank=True, null=True, verbose_name='Energia (Kcal)')),
                ('umidade', models.FloatField(blank=True, null=True, verbose_name='Umidade (g)')),
                ('cinzas', models.FloatField(blank=True, null=True, verbose_name='Cinzas (g)')),
                ('alcool', models.FloatField(blank=True, null=True, verbose_name='Álcool (g)')),
                ('sal_adicao', models.FloatField(blank=True, null=True, verbose_name='Sal de adição (g)')),
                ('acucar_adicao', models.FloatField(blank=True, null=True, verbose_name='Açúcar de adição (g)')),
                ('carboidrato_total', models.FloatField(blank=True, null=True, verbose_name='Carboidrato total (g)')),
                ('carboidrato_disponivel', models.FloatField(blank=True, null=True, verbose_name='Carboidrato disponível (g)')),
                ('proteina', models.FloatField(blank=True, null=True, verbose_name='Proteína (g)')),
                ('lipidios', models.FloatField(blank=True, null=True, verbose_name='Lipídios (g)')),
                ('fibra_alimentar', models.FloatField(blank=True, null=True, verbose_name='Fibra alimentar (g)')),
                ('colesterol', models.FloatField(blank=True, null=True, verbose_name='Colesterol (mg)')),
                ('acidos_graxos_saturados', models.FloatField(blank=True, null=True, verbose_name='Saturados (g)')),
                ('acidos_graxos_monoinsaturados', models.FloatField(blank=True, null=True, verbose_name='Monoinsaturados (g)')),
                ('acidos_graxos_polinsaturados', models.FloatField(blank=True, null=True, verbose_name='Polinsaturados (g)')),
                ('acidos_graxos_trans', models.FloatField(blank=True, null=True, verbose_name='Trans (g)')),
                ('calcio', models.FloatField(blank=True, null=True, verbose_name='Cálcio (mg)')),
                ('ferro', models.FloatField(blank=True, null=True, verbose_name='Ferro (mg)')),
                ('sodio', models.FloatField(blank=True, null=True, verbose_name='Sódio (mg)')),
                ('magnesio', models.FloatField(blank=True, null=True, verbose_name='Magnésio (mg)')),
                ('fosforo', models.FloatField(blank=True, null=True, verbose_name='Fósforo (mg)')),
                ('potassio', models.FloatField(blank=True, null=True, verbose_name='Potássio (mg)')),
                ('zinco', models.FloatField(blank=True, null=True, verbose_name='Zinco (mg)')),
                ('cobre', models.FloatField(blank=True, null=True, verbose_name='Cobre (mg)')),
                ('selenio', models.FloatField(blank=True, null=True, verbose_name='Selênio (mcg)')),
                ('vitamina_a_re', models.FloatField(blank=True, null=True, verbose_name='Vitamina A (RE)')),
                ('vitamina_a_rae', models.FloatField(blank=True, null=True, verbose_name='Vitamina A (RAE)')),
                ('vitamina_d', models.FloatField(blank=True, null=True, verbose_name='Vitamina D (mcg)')),
                ('vitamina_e_alfa_toceferol', models.FloatField(blank=True, null=True, verbose_name='Vitamina E (mg)')),
                ('vitamina_b1_tiamina', models.FloatField(blank=True, null=True, verbose_name='Tiamina B1 (mg)')),
                ('vitamina_b2_riboflavina', models.FloatField(blank=True, null=True, verbose_name='Riboflavina B2 (mg)')),
                ('vitamina_b3_niacina', models.FloatField(blank=True, null=True, verbose_name='Niacina B3 (mg)')),
                ('vitamina_b6', models.FloatField(blank=True, null=True, verbose_name='Vitamina B6 (mg)')),
                ('vitamina_b12', models.FloatField(blank=True, null=True, verbose_name='Vitamina B12 (mcg)')),
                ('vitamina_c', models.FloatField(blank=True, null=True, verbose_name='Vitamina C (mg)')),
                ('vitamina_b9', models.FloatField(blank=True, null=True, verbose_name='Folato B9 (mcg)')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_alimentos/', verbose_name='Foto do Alimento')),
            ],
        ),
    ]
