# Generated by Django 5.2.11 on 2026-03-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='excluido',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
    ]
