# Generated by Django 5.2.11 on 2026-03-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0002_alimento_excluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='nome',
            field=models.CharField(max_length=1000, verbose_name='Alimento'),
        ),
    ]
