# Generated by Django 5.2.11 on 2026-03-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0003_alter_alimento_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='is_receita',
            field=models.BooleanField(default=False, verbose_name='É uma receita?'),
        ),
    ]
