# Generated by Django 5.2.11 on 2026-03-29 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0004_alimento_is_receita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alimento',
            old_name='is_receita',
            new_name='receita',
        ),
    ]
