# Generated by Django 5.2.11 on 2026-03-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0005_rename_is_receita_alimento_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='acidos_graxos_monoinsaturados',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Monoinsaturados (g)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='acidos_graxos_polinsaturados',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Polinsaturados (g)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='acidos_graxos_saturados',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Saturados (g)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='acidos_graxos_trans',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Trans (g)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='acucar_adicao',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Açúcar de adição (g)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='alcool',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Álcool (g)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='calcio',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Cálcio (mg)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='carboidrato_disponivel',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Carboidrato disponível (g)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='carboidrato_total',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Carboidrato total (g)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='cinzas',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Cinzas (g)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='cobre',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Cobre (mg)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='colesterol',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Colesterol (mg)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='energia_kcal',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Energia (Kcal)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='energia_kj',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Energia (KJ)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='ferro',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Ferro (mg)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='fibra_alimentar',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Fibra alimentar (g)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='fosforo',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Fósforo (mg)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='foto',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='fotos_alimentos/', verbose_name='Foto do Alimento'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='lipidios',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Lipídios (g)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='magnesio',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Magnésio (mg)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='potassio',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Potássio (mg)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='proteina',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Proteína (g)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='sal_adicao',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Sal de adição (g)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='selenio',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Selênio (mcg)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='sodio',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Sódio (mg)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='umidade',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Umidade (g)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='vitamina_a_rae',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Vitamina A (RAE)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='vitamina_a_re',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Vitamina A (RE)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='vitamina_b12',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Vitamina B12 (mcg)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='vitamina_b1_tiamina',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Tiamina B1 (mg)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='vitamina_b2_riboflavina',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Riboflavina B2 (mg)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='vitamina_b3_niacina',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Niacina B3 (mg)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='vitamina_b6',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Vitamina B6 (mg)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='vitamina_b9',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Folato B9 (mcg)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='vitamina_c',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Vitamina C (mg)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='vitamina_d',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Vitamina D (mcg)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='vitamina_e_alfa_toceferol',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Vitamina E (mg)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='zinco',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Zinco (mg)'),
        ),
    ]
