# Generated by Django 5.2.11 on 2026-03-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0006_alter_alimento_acidos_graxos_monoinsaturados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='visualizacoes',
            field=models.IntegerField(default=0, verbose_name='Visualizações'),
        ),
    ]
