# Generated by Django 5.2.11 on 2026-04-12 20:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0007_alimento_visualizacoes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Dieta para Hipertrofia', max_length=100)),
                ('data', models.DateField(default=django.utils.timezone.now, help_text='Data desta rotina')),
                ('descricao', models.TextField(blank=True, help_text='Anotações extras', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotinas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemRotina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refeicao', models.CharField(choices=[('cafe', 'Café da Manhã'), ('almoco', 'Almoço'), ('lanche', 'Lanche da Tarde'), ('jantar', 'Jantar')], max_length=20)),
                ('quantidade_gramas', models.DecimalField(decimal_places=2, help_text='Quantidade em gramas', max_digits=6)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutri.alimento')),
                ('rotina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='nutri.rotina')),
            ],
        ),
    ]
