# Generated by Django 5.2.11 on 2026-04-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0008_rotina_itemrotina'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrotina',
            name='excluido',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
        migrations.AddField(
            model_name='rotina',
            name='excluido',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
    ]
